# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include:
     - 'main'
  paths:
    include:
      - 'cs/PSUbi.TestModule/**'
      - 'cs/PSUbi.TestModule.Tests/**'
      - 'pwsh/PSUbi.TestModule/**'

pool:
  vmImage: windows-latest

steps:
- checkout: self
  displayName: 'Checkout GIT'
  clean: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'cs/PSUbi.TestModule/*.csproj'
    arguments: '--framework net481 -o pwsh/PSUbi.TestModule/lib/net481'
    zipAfterPublish: false
    modifyOutputPath: false