# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-net
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-powershell

name: Release .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/dotnet-release.yml"
    tags: [ "release/*" ]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
    - name: Checkout GIT
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/psteniusubi/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore .NET
      run: dotnet restore cs/PSUbi.TestModule
    - name: Build .NET
      run: dotnet build --no-restore --configuration Release cs/PSUbi.TestModule
    - name: Package .NET
      run: dotnet pack --no-build --configuration Release cs/PSUbi.TestModule
    - name: Release .NET
      run: gh release create --draft "$GITHUB_REF_NAME" cs/PSUbi.TestModule/bin/Release/*.nupkg
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Push .NET
      run: dotnet nuget push --skip-duplicate --api-key "$NUGET_AUTH_TOKEN" cs/PSUbi.TestModule/bin/Release/*.nupkg
