# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish package (PSUbi.TestModule)

on:
  release:
    types: [created]

jobs:
  dotnet-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/psteniusubi/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore cs/PSUbi.TestModule
    - name: Build .NET
      run: dotnet build --no-restore --configuration Release cs/PSUbi.TestModule
    - name: Package .NET
      run: dotnet pack --configuration Release cs/PSUbi.TestModule
    - name: Publish .NET
      run: dotnet nuget push cs/PSUbi.TestModule/bin/Release/*.nupkg
    - name: Package PWSH
      run: dotnet publish --no-build --framework net8.0 --configuration Release cs/PSUbi.TestModule -o pwsh/PSUbi.TestModule/lib/net80
    - name: Publish PWSH
      shell: pwsh
      run: |
        Publish-Module -Path pwsh/PSUbi.TestModule/PSUbi.TestModule.psd1 -NuGetApiKey $env:NUGET_AUTH_TOKEN -Verbose
