# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-powershell

name: Test PowerShell (PSUbi.TestModule)

on:
  push:
    branches: [ "main" ]
    paths:
      - "cs/PSUbi.TestModule/**"
      - "pwsh/PSUbi.TestModule/**"
      - ".github/workflows/powershell-test.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "cs/PSUbi.TestModule/**"
      - "pwsh/PSUbi.TestModule/**"
      - ".github/workflows/powershell-test.yml"

jobs:
  powershell-test:
    runs-on: windows-latest
    steps:
    - name: Checkout GIT
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install .NET Framework
      shell: pwsh
      run: |
        Invoke-WebRequest "https://go.microsoft.com/fwlink/?linkid=2203306" -OutFile sdk.exe
        .\sdk.exe /passive /AcceptEULA /norestart
    - name: Package PWSH
      run: dotnet publish --framework net4.81 --configuration Release cs/PSUbi.TestModule -o pwsh/PSUbi.TestModule/lib/net481
    - name: Test PWSH
      shell: powershell
      run: |
          Invoke-Pester pwsh/PSUbi.TestModule -PassThru
