# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-powershell

name: Test (PSUbi.TestModule)

on:
  push:
    branches: [ "main" ]
    paths:
      - "cs/PSUbi.TestModule/**"
      - "pwsh/PSUbi.TestModule/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "cs/PSUbi.TestModule/**"
      - "pwsh/PSUbi.TestModule/**"

jobs:
  pwsh-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Package PWSH
      run: dotnet publish --framework net8.0 --configuration Release cs/PSUbi.TestModule -o pwsh/PSUbi.TestModule/lib/net80
    - name: Test PWSH
      shell: pwsh
      run: |
          Invoke-Pester pwsh/PSUbi.TestModule -PassThru
